importing necessary libraries

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [73]:
df = pd.read_csv(r"C:\Users\rishi\Desktop\CodSoft\fraudTrain.csv.zip")
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [74]:
df.info

<bound method DataFrame.info of          Unnamed: 0 trans_date_trans_time               cc_num  \
0                 0   2019-01-01 00:00:18     2703186189652095
1                 1   2019-01-01 00:00:44         630423337322
2                 2   2019-01-01 00:00:51       38859492057661
3                 3   2019-01-01 00:01:16     3534093764340240
4                 4   2019-01-01 00:03:06      375534208663984
...             ...                   ...                  ...
1296670     1296670   2020-06-21 12:12:08       30263540414123
1296671     1296671   2020-06-21 12:12:19     6011149206456997
1296672     1296672   2020-06-21 12:12:32     3514865930894695
1296673     1296673   2020-06-21 12:13:36     2720012583106919
1296674     1296674   2020-06-21 12:13:37  4292902571056973207

                                    merchant       category     amt  \
0                 fraud_Rippin, Kub and Mann       misc_net    4.97
1            fraud_Heller, Gutmann and Zieme    grocery_pos  107.23
2                       fraud_Lind-Buckridge  entertainment  220.11
3         fraud_Kutch, Hermiston and Farrell  gas_transport   45.00
4                        fraud_Keeling-Crist       misc_pos   41.96
...                                      ...            ...     ...
1296670                    fraud_Reichel Inc  entertainment   15.56
1296671             fraud_Abernathy and Sons    food_dining   51.70
1296672                 fraud_Stiedemann Ltd    food_dining  105.93
1296673  fraud_Reinger, Weissnat and Strosin    food_dining   74.90
1296674  fraud_Langosh, Wintheiser and Hyatt    food_dining    4.30

               first       last gender                         street  ...  \
0           Jennifer      Banks      F                 561 Perry Cove  ...
1          Stephanie       Gill      F   43039 Riley Greens Suite 393  ...
2             Edward    Sanchez      M       594 White Dale Suite 530  ...
3             Jeremy      White      M    9443 Cynthia Court Apt. 038  ...
4              Tyler     Garcia      M               408 Bradley Rest  ...
...              ...        ...    ...                            ...  ...
1296670         Erik  Patterson      M       162 Jessica Row Apt. 072  ...
1296671      Jeffrey      White      M  8617 Holmes Terrace Suite 651  ...
1296672  Christopher  Castaneda      M     1632 Cohen Drive Suite 639  ...
1296673       Joseph     Murray      M           42933 Ryan Underpass  ...
1296674      Jeffrey      Smith      M           135 Joseph Mountains  ...

             lat      long  city_pop                                job  \
0        36.0788  -81.1781      3495          Psychologist, counselling
1        48.8878 -118.2105       149  Special educational needs teacher
2        42.1808 -112.2620      4154        Nature conservation officer
3        46.2306 -112.1138      1939                    Patent attorney
4        38.4207  -79.4629        99     Dance movement psychotherapist
...          ...       ...       ...                                ...
1296670  37.7175 -112.4777       258                       Geoscientist
1296671  39.2667  -77.5101       100   Production assistant, television
1296672  32.9396 -105.8189       899                    Naval architect
1296673  43.3526 -102.5411      1126              Volunteer coordinator
1296674  45.8433 -113.8748       218           Therapist, horticultural

                dob                         trans_num   unix_time  merch_lat  \
0        1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293
1        1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047
2        1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704
3        1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331
4        1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999
...             ...                               ...         ...        ...
1296670  1961-11-24  440b587732da4dc1a6395aba5fb41669  1371816728  36.841266
1296671  1979-12-11  278000d2e0d2277d1de2f890067dcc0a  1371816739  38.906881
1296672  1967-08-30  483f52fe67fabef353d552c1e662974c  1371816752  33.619513
1296673  1980-08-18  d667cdcbadaaed3da3f4020e83591c83  1371816816  42.788940
1296674  1995-08-16  8f7c8e4ab7f25875d753b422917c98c9  1371816817  46.565983

         merch_long  is_fraud
0        -82.048315         0
1       -118.186462         0
2       -112.154481         0
3       -112.561071         0
4        -78.632459         0
...             ...       ...
1296670 -111.690765         0
1296671  -78.246528         0
1296672 -105.130529         0
1296673 -103.241160         0
1296674 -114.186110         0

[1296675 rows x 23 columns]>

In [75]:
df = df.head(20000)

cleaning the data

CLEANING THE DATA

In [76]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [77]:
df.drop_duplicates()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,2019-01-13 04:26:59,4104312520615374,fraud_McDermott-Weimann,grocery_pos,98.86,Brooke,Rodriguez,F,901 Todd Gardens Apt. 466,...,33.6401,-116.5567,1661,"Therapist, music",1988-09-19,61f67fbe54c4bc1afc847fdb1c58cc4a,1326428819,33.767565,-117.341778,0
19996,19996,2019-01-13 04:28:22,30343344410970,"fraud_Bernhard, Grant and Langworth",shopping_pos,2.04,Jacob,Dawson,M,663 Anna Plaza,...,41.4622,-79.1306,4172,"Copywriter, advertising",1962-03-20,6b36f682b3a482fe9ea446c4a0c88dc3,1326428902,40.594885,-79.119914,0
19997,19997,2019-01-13 04:29:06,3502088871723054,fraud_Shields Inc,grocery_net,38.52,Scott,Martin,M,31472 Cody Place Suite 740,...,39.0298,-77.0793,19054,Operations geologist,1976-09-08,5f84d53d8465a2c6493a336046c13e83,1326428946,39.552430,-77.582253,0
19998,19998,2019-01-13 04:29:29,2706977570537524,fraud_Hudson-Ratke,grocery_pos,110.12,David,Serrano,M,4739 Martin Common,...,39.2830,-82.3977,341,Accounting technician,1978-12-18,52a066480aa8bcf61c5485423c31d880,1326428969,38.402828,-82.689669,0
19999,19999,2019-01-13 04:30:44,345389171551808,fraud_Kling Inc,gas_transport,52.22,Justin,Fowler,M,5569 Phillips Neck Apt. 003,...,33.9215,-89.6782,3451,Financial trader,1984-05-19,8514845414a2918933ba678536559800,1326429044,33.942943,-90.217408,0

In [78]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [79]:
df["merchant"].unique()

array(['fraud_Rippin, Kub and Mann', 'fraud_Heller, Gutmann and Zieme',
       'fraud_Lind-Buckridge', 'fraud_Kutch, Hermiston and Farrell',
       'fraud_Keeling-Crist', 'fraud_Stroman, Hudson and Erdman',
       'fraud_Rowe-Vandervort', 'fraud_Corwin-Collins',
       'fraud_Herzog Ltd', 'fraud_Schoen, Kuphal and Nitzsche',
       'fraud_Rutherford-Mertz', 'fraud_Kerluke-Abshire',
       'fraud_Lockman Ltd', 'fraud_Kiehn Inc', 'fraud_Beier-Hyatt',
       'fraud_Schmidt and Sons', 'fraud_Lebsack and Sons',
       'fraud_Mayert Group', 'fraud_Konopelski, Schneider and Hartmann',
       'fraud_Schultz, Simonis and Little', 'fraud_Bauch-Raynor',
       'fraud_Harris Inc', 'fraud_Kling-Grant', 'fraud_Pacocha-Bauch',
       'fraud_Lesch Ltd', 'fraud_Kunde-Sanford', "fraud_Deckow-O'Conner",
       'fraud_Bruen-Yost', 'fraud_Kunze Inc',
       'fraud_Nitzsche, Kessler and Wolff',
       'fraud_Kihn, Abernathy and Douglas', 'fraud_Torphy-Goyette',
       'fraud_Balistreri-Nader', 'fraud_Bahringer, Schoen and Corkery',
       'fraud_Hudson-Ratke', 'fraud_Heidenreich PLC',
       'fraud_Halvorson Group', 'fraud_Harber Inc',
       'fraud_Mosciski, Gislason and Mertz',
       'fraud_Christiansen, Goyette and Schamberger', 'fraud_Howe Ltd',
       'fraud_Ledner-Pfannerstill', 'fraud_Koepp-Witting',
       'fraud_Doyle Ltd', 'fraud_Schaefer, Maggio and Daugherty',
       'fraud_Stracke-Lemke', 'fraud_Mosciski, Ziemann and Farrell',
       'fraud_Cartwright-Harris', "fraud_Pacocha-O'Reilly",
       'fraud_Pfeffer LLC', 'fraud_Huels-Hahn', 'fraud_Volkman PLC',
       'fraud_Kiehn-Emmerich', 'fraud_Kemmer-Buckridge',
       'fraud_Cummerata-Jones', 'fraud_Goldner, Kovacek and Abbott',
       'fraud_Spinka-Welch', 'fraud_Huel-Langworth',
       'fraud_Macejkovic-Lesch', 'fraud_Morar Inc',
       'fraud_Eichmann, Bogan and Rodriguez',
       'fraud_Huel, Hammes and Witting', 'fraud_Ferry, Lynch and Kautzer',
       'fraud_Heathcote LLC', 'fraud_Little, Gutmann and Lynch',
       'fraud_Jaskolski-Dibbert', 'fraud_Hackett-Lueilwitz',
       'fraud_Cummings LLC', 'fraud_Swaniawski, Lowe and Robel',
       'fraud_Osinski, Ledner and Leuschke',
       'fraud_Reichert, Huels and Hoppe', 'fraud_Ankunding LLC',
       'fraud_Pfeffer and Sons', 'fraud_Greenholt, Jacobi and Gleason',
       'fraud_Connelly, Reichert and Fritsch', 'fraud_Torp-Labadie',
       'fraud_Wolf Inc', 'fraud_VonRueden Group', 'fraud_Vandervort-Funk',
       'fraud_Bernhard Inc', 'fraud_Morissette, Weber and Wiegand',
       'fraud_Brekke and Sons', 'fraud_Mraz-Herzog',
       'fraud_Padberg-Welch', 'fraud_Kutch-Hegmann',
       'fraud_Corwin-Gorczany', 'fraud_Huels-Nolan', 'fraud_DuBuque LLC',
       'fraud_Schmeler Inc', 'fraud_Schaefer, McGlynn and Bosco',
       'fraud_Williamson LLC', 'fraud_Pouros-Conroy',
       'fraud_Erdman-Kertzmann', 'fraud_Kuhn LLC',
       'fraud_Fisher-Schowalter', 'fraud_Medhurst PLC',
       'fraud_Kerluke Inc', 'fraud_Stark-Batz',
       'fraud_Gottlieb, Considine and Schultz',
       'fraud_Adams, Kovacek and Kuhlman', 'fraud_Grimes LLC',
       'fraud_Rodriguez Group', 'fraud_Wuckert-Walter',
       'fraud_Weber and Sons', 'fraud_Herman, Treutel and Dickens',
       'fraud_Rau and Sons', 'fraud_Koss and Sons',
       'fraud_Smitham-Schiller', 'fraud_Hills-Olson', 'fraud_Durgan-Auer',
       'fraud_McDermott-Rice', 'fraud_Raynor, Reinger and Hagenes',
       'fraud_Powlowski-Weimann', 'fraud_Langosh, Wintheiser and Hyatt',
       'fraud_Baumbach, Hodkiewicz and Walsh', 'fraud_Rempel Inc',
       'fraud_Bins-Rice', 'fraud_Emard Inc', 'fraud_Kutch and Sons',
       'fraud_Fisher Inc', 'fraud_Olson, Becker and Koch',
       "fraud_Friesen-D'Amore", 'fraud_Reilly, Heaney and Cole',
       'fraud_Boyer PLC', 'fraud_Luettgen PLC', 'fraud_Cassin-Harvey',
       'fraud_Funk Group', 'fraud_Goodwin-Nitzsche',
       'fraud_Parisian, Schiller and Altenwerth', 'fraud_Metz-Boehm',
       'fraud_Monahan, Bogisich and Ledner', 'fraud_Koelpin and Sons',
       'fraud_Kuhic LLC', 'fraud_Koepp-Parker',
       'fraud_Stehr, Jewess and Schimmel',
       'fraud_Quitzon, Green and Bashirian',
       'fraud_Nicolas, Hills and McGlynn', 'fraud_Leannon-Ward',
       'fraud_Friesen-Stamm', 'fraud_Botsford Ltd', 'fraud_Bradtke PLC',
       'fraud_Zieme, Bode and Dooley', 'fraud_Hills-Witting',
       'fraud_Brown-Greenholt', 'fraud_Bernhard, Grant and Langworth',
       'fraud_Wiza, Schaden and Stark', 'fraud_Buckridge PLC',
       'fraud_Kilback LLC', 'fraud_Spinka Inc',
       'fraud_Kerluke, Kertzmann and Wiza',
       'fraud_Ferry, Reichel and DuBuque', 'fraud_Price Inc',
       'fraud_Johnston, Nikolaus and Maggio', 'fraud_Berge LLC',
       'fraud_Conroy-Cruickshank', 'fraud_Abshire PLC',
       'fraud_Gleason-Macejkovic', 'fraud_McGlynn-Jaskolski',
       'fraud_Bartoletti-Wunsch', 'fraud_Cole PLC',
       'fraud_Lehner, Reichert and Mills', 'fraud_McCullough LLC',
       'fraud_Schmitt Ltd', 'fraud_Pouros-Haag',
       'fraud_Strosin-Cruickshank', 'fraud_Weimann, Kuhic and Beahan',
       'fraud_Donnelly PLC', 'fraud_Lockman, West and Runte',
       'fraud_Torp-Lemke', 'fraud_Kris-Weimann',
       'fraud_Rodriguez, Yost and Jenkins', 'fraud_Wiegand-Lowe',
       'fraud_Auer-Mosciski', 'fraud_Okuneva, Schneider and Rau',
       'fraud_Kassulke PLC', 'fraud_Dach-Nader', 'fraud_Cummings Group',
       'fraud_Reichert, Shanahan and Hayes',
       'fraud_Tromp, Kerluke and Glover',
       'fraud_Bins, Balistreri and Beatty', 'fraud_Trantow PLC',
       'fraud_Miller-Hauck', 'fraud_Kuvalis Ltd', 'fraud_Dickinson Ltd',
       'fraud_Stanton, Jakubowski and Baumbach',
       'fraud_Rohan, White and Aufderhar',
       'fraud_Cormier, Stracke and Thiel',
       'fraud_Tillman, Fritsch and Schmitt',
       'fraud_Christiansen-Gusikowski',
       'fraud_Jenkins, Hauck and Friesen', 'fraud_Reichel Inc',
       'fraud_Prohaska-Murray', 'fraud_Parker, Nolan and Trantow',
       'fraud_Volkman Ltd', 'fraud_Streich, Hansen and Veum',
       'fraud_Kutch LLC', 'fraud_Barton Inc', 'fraud_Dooley-Thompson',
       'fraud_Flatley Group', 'fraud_Turcotte-Halvorson',
       'fraud_Lynch Ltd', 'fraud_Romaguera, Cruickshank and Greenholt',
       'fraud_Gutmann Ltd', 'fraud_Sporer Inc',
       'fraud_Runolfsson and Sons', 'fraud_Block Group',
       'fraud_Bahringer-Larson', 'fraud_Rowe, Batz and Goodwin',
       'fraud_Schmitt Inc', 'fraud_Maggio-Fahey',
       'fraud_Haley, Jewess and Bechtelar',
       'fraud_Ruecker, Beer and Collier',
       'fraud_Robel, Cummerata and Prosacco', 'fraud_Jast-McDermott',
       'fraud_Bernier, Volkman and Hoeger', 'fraud_Heaney-Marquardt',
       'fraud_Hudson-Grady', 'fraud_Towne, Walker and Borer',
       'fraud_Terry-Huel', 'fraud_Kihn-Fritsch', 'fraud_Eichmann-Russel',
       'fraud_Miller-Harris', 'fraud_Schumm PLC',
       'fraud_Greenfelder, Bartoletti and Davis',
       'fraud_Kovacek, Dibbert and Ondricka', 'fraud_Hermann-Gaylord',
       'fraud_Bailey-Morar', 'fraud_McDermott-Weimann', 'fraud_Welch Inc',
       'fraud_Auer-West', 'fraud_Boehm, Predovic and Reinger',
       'fraud_Dibbert and Sons', 'fraud_Lind, Huel and McClure',
       'fraud_Casper, Hand and Zulauf', 'fraud_McCullough Group',
       'fraud_Streich, Dietrich and Barton', "fraud_O'Keefe-Hudson",
       'fraud_Pagac LLC', 'fraud_Bernier, Streich and Jewess',
       "fraud_Greenholt, O'Hara and Balistreri", 'fraud_Dickinson-Rempel',
       'fraud_Dare-Marvin', 'fraud_Spencer PLC', 'fraud_Stamm-Rodriguez',
       'fraud_Langworth, Boehm and Gulgowski',
       'fraud_Larkin, Stracke and Greenfelder',
       'fraud_Yost, Block and Koepp',
       'fraud_Douglas, Schneider and Turner', 'fraud_Kuphal-Predovic',
       'fraud_Parisian and Sons', 'fraud_Flatley-Durgan',
       'fraud_Gislason Group', 'fraud_Bednar Group',
       'fraud_Heller-Langosh', 'fraud_Zboncak Ltd', 'fraud_Gerlach Inc',
       'fraud_Wilkinson Ltd', 'fraud_Moen, Reinger and Murphy',
       'fraud_Kerluke, Considine and Macejkovic', 'fraud_Upton PLC',
       'fraud_Bogisich Inc', 'fraud_Marks Inc', 'fraud_Murray-Smitham',
       'fraud_Frami Group', 'fraud_Ortiz Group', 'fraud_Goldner-Lemke',
       'fraud_Hickle Group', 'fraud_Conroy Ltd',
       'fraud_Schumm, Bauch and Ondricka', 'fraud_McGlynn-Heathcote',
       'fraud_Herman Inc', 'fraud_Gutmann-Upton',
       'fraud_Volkman-Predovic',
       'fraud_Wintheiser, Dietrich and Schimmel',
       'fraud_Raynor, Feest and Miller', 'fraud_Bogisich-Homenick',
       'fraud_Jast and Sons', 'fraud_Baumbach, Strosin and Nicolas',
       'fraud_Towne, Greenholt and Koepp', "fraud_Schamberger-O'Keefe",
       'fraud_Nienow PLC', 'fraud_Emmerich-Luettgen', 'fraud_Mante Group',
       'fraud_Baumbach, Feeney and Morar', 'fraud_Thiel PLC',
       'fraud_Mohr Inc', 'fraud_Hagenes, Kohler and Hoppe',
       'fraud_Block-Parisian', 'fraud_Dooley Inc',
       'fraud_Bashirian Group', 'fraud_Cremin, Hamill and Reichel',
       'fraud_Sawayn PLC', 'fraud_Jewess LLC', 'fraud_Roberts-Beahan',
       'fraud_Brown PLC', 'fraud_Tillman, Dickinson and Labadie',
       'fraud_Reichert, Rowe and Mraz', 'fraud_Kilback Group',
       'fraud_Spencer-Runolfsson', 'fraud_Labadie, Treutel and Bode',
       'fraud_Dach-Borer', 'fraud_Johnson, Runolfsdottir and Mayer',
       'fraud_Smitham-Boehm', 'fraud_Moore, Dibbert and Koepp',
       'fraud_Hamill-Daugherty', 'fraud_Watsica, Haag and Considine',
       'fraud_Smith-Stokes', 'fraud_Kuhic, Bins and Pfeffer',
       'fraud_Nader-Heller', 'fraud_Kozey-Boehm', 'fraud_Stiedemann Inc',
       'fraud_Lehner, Mosciski and King', 'fraud_Reynolds-Schinner',
       'fraud_Koss, McLaughlin and Mayer', 'fraud_Terry, Johns and Bins',
       'fraud_Kemmer-Reinger', 'fraud_Larson-Moen', 'fraud_Kuhic Inc',
       'fraud_Kris-Padberg', 'fraud_Schmeler, Bashirian and Price',
       'fraud_Klocko LLC', 'fraud_Schaefer, Fay and Hilll',
       'fraud_Kling Inc', 'fraud_Turner and Sons', 'fraud_Mohr-Bayer',
       'fraud_Wiza LLC', 'fraud_Skiles-Ankunding',
       'fraud_Jaskolski-Vandervort', 'fraud_Kerluke PLC',
       'fraud_Ernser-Lynch', 'fraud_Zboncak, Rowe and Murazik',
       'fraud_Stoltenberg-Beatty', 'fraud_Kuphal-Bartoletti',
       'fraud_Rempel PLC', 'fraud_Denesik and Sons', 'fraud_Goyette Inc',
       'fraud_Dicki Ltd', 'fraud_Stokes, Christiansen and Sipes',
       'fraud_Hermann and Sons', 'fraud_Gibson-Deckow',
       'fraud_Douglas-White', 'fraud_Murray Ltd', 'fraud_McKenzie-Huels',
       'fraud_Runte-Mohr', 'fraud_Roob, Conn and Tremblay',
       'fraud_Boyer-Reichert', 'fraud_Shanahan-Lehner',
       'fraud_Greenholt Ltd', 'fraud_Kulas Group',
       'fraud_Dare, Fritsch and Zboncak', 'fraud_Waters-Cruickshank',
       'fraud_Kunze, Larkin and Mayert', 'fraud_Bednar Inc',
       'fraud_Schimmel-Olson', 'fraud_Lubowitz, Terry and Stracke',
       'fraud_Schoen-Quigley', 'fraud_Kihn-Schuster',
       'fraud_Padberg-Rogahn', 'fraud_Lynch-Mohr', 'fraud_Hilpert-Conroy',
       'fraud_Jacobi Inc', 'fraud_Berge, Kautzer and Harris',
       'fraud_Hammes-Beatty', 'fraud_Gulgowski LLC',
       'fraud_Schuppe, Nolan and Hoeger', 'fraud_Pollich LLC',
       'fraud_Bernier and Sons', 'fraud_Wilkinson PLC',
       'fraud_Kling-Ernser', "fraud_O'Connell, Botsford and Hand",
       'fraud_Little-Gleichner', 'fraud_Champlin and Sons',
       'fraud_Hoppe-Parisian', 'fraud_Schuppe LLC', 'fraud_Emmerich-Rau',
       'fraud_Beier LLC', 'fraud_Champlin-Casper', 'fraud_Gerhold LLC',
       'fraud_Renner Ltd', 'fraud_Gaylord-Powlowski',
       'fraud_Prosacco, Kreiger and Kovacek', 'fraud_Eichmann-Kilback',
       "fraud_O'Hara-Wilderman", 'fraud_Terry Ltd',
       'fraud_Beier and Sons', "fraud_O'Keefe-Wisoky",
       'fraud_Simonis-Prohaska', 'fraud_Breitenberg-Hermiston',
       'fraud_Brown Inc', 'fraud_Fahey Inc',
       'fraud_Boehm, Block and Jakubowski',
       'fraud_Mante, Luettgen and Hackett', 'fraud_Thompson-Gleason',
       'fraud_Turcotte, Batz and Buckridge',
       'fraud_Goyette, Howell and Collier',
       'fraud_Jones, Sawayn and Romaguera', 'fraud_Medhurst Inc',
       'fraud_Bode-Schuster', 'fraud_Connelly-Carter',
       'fraud_Gottlieb-Hansen', 'fraud_Schroeder, Wolff and Hermiston',
       'fraud_Hettinger, McCullough and Fay',
       'fraud_Pouros, Walker and Spencer', 'fraud_Kub PLC',
       'fraud_Watsica LLC', 'fraud_Stiedemann Ltd',
       'fraud_Hauck, Dietrich and Funk', 'fraud_Labadie LLC',
       'fraud_Friesen Inc', 'fraud_Crist, Jakubowski and Littel',
       'fraud_Hodkiewicz, Prohaska and Paucek',
       'fraud_McDermott, Osinski and Morar', 'fraud_Fritsch and Sons',
       'fraud_Swaniawski, Nitzsche and Welch',
       'fraud_Windler, Goodwin and Kovacek',
       'fraud_Yost, Schamberger and Windler',
       'fraud_Metz, Russel and Metz', 'fraud_Erdman-Durgan',
       'fraud_Bahringer, Bergnaum and Quitzon', 'fraud_Veum-Koelpin',
       'fraud_Becker, Harris and Harvey', 'fraud_Monahan-Morar',
       'fraud_Johns Inc', 'fraud_Mosciski Group', 'fraud_Abbott-Steuber',
       'fraud_Schaefer Ltd', 'fraud_Dibbert-Green',
       'fraud_Weimann-Lockman', 'fraud_Kub-Heaney', 'fraud_Zulauf LLC',
       'fraud_Ratke and Sons', 'fraud_Jakubowski Inc', 'fraud_Beer-Jast',
       'fraud_Kautzer and Sons', 'fraud_Feil-Morar',
       'fraud_Johnston-Casper', 'fraud_Medhurst, Labadie and Gottlieb',
       "fraud_Lesch, D'Amore and Brown", 'fraud_Botsford PLC',
       'fraud_Bins-Howell', 'fraud_Kihn Inc',
       'fraud_Hartmann, Rowe and Hermann', 'fraud_Towne LLC',
       'fraud_Lynch-Wisozk', 'fraud_Kutch-Ferry', 'fraud_Goyette-Gerhold',
       'fraud_Bradtke, Torp and Bahringer', 'fraud_Homenick LLC',
       'fraud_Zemlak, Tillman and Cremin',
       'fraud_Schneider, Hayes and Nikolaus',
       'fraud_Schumm, McLaughlin and Carter', 'fraud_Nader-Maggio',
       'fraud_Haley, Batz and Auer', 'fraud_Yost-Rogahn',
       'fraud_Schoen, Nienow and Bauch',
       'fraud_Ledner, Hartmann and Feest', 'fraud_Collier LLC',
       'fraud_Schuppe-Schuppe', 'fraud_Walter, Hettinger and Kessler',
       'fraud_Bechtelar-Rippin', "fraud_Hamill-D'Amore",
       'fraud_Swift PLC', 'fraud_Cronin, Kshlerin and Weber',
       'fraud_Romaguera, Wehner and Tromp',
       'fraud_Feil, Hilpert and Koss', 'fraud_White and Sons',
       'fraud_Mueller, Gerhold and Mueller', 'fraud_Botsford and Sons',
       'fraud_Kirlin and Sons', 'fraud_Bednar PLC',
       'fraud_Runolfsdottir, Mueller and Hand', 'fraud_Kuphal-Toy',
       'fraud_Bahringer-Streich', 'fraud_Wuckert, Wintheiser and Friesen',
       'fraud_Crona and Sons', 'fraud_Prosacco LLC', 'fraud_Schiller Ltd',
       'fraud_Waelchi-Wolf', 'fraud_Torphy-Kertzmann',
       'fraud_McCullough, Hudson and Schuster', 'fraud_Baumbach Ltd',
       'fraud_Schiller, Blanda and Johnson', 'fraud_Cartwright PLC',
       'fraud_Reilly LLC', 'fraud_Cruickshank-Mills',
       'fraud_Altenwerth, Cartwright and Koss',
       'fraud_Effertz, Welch and Schowalter',
       'fraud_Klocko, Runolfsdottir and Breitenberg',
       'fraud_Ruecker-Mayert', 'fraud_Schroeder, Hauck and Treutel',
       'fraud_Lemke-Gutmann', 'fraud_Graham, Hegmann and Hammes',
       'fraud_Reilly and Sons', 'fraud_Stark-Koss', 'fraud_Daugherty LLC',
       'fraud_Denesik, Powlowski and Pouros', 'fraud_Rippin-VonRueden',
       'fraud_Heller PLC', 'fraud_Hills-Boyer', 'fraud_Cormier LLC',
       'fraud_Erdman-Ebert', 'fraud_Bogisich-Weimann',
       'fraud_Gutmann, McLaughlin and Wiza', 'fraud_Little Ltd',
       'fraud_Bode-Rempel', 'fraud_Kutch, Steuber and Gerhold',
       'fraud_Kessler Inc', 'fraud_Deckow-Dare', 'fraud_Rolfson-Kunde',
       'fraud_Marvin-Lind', 'fraud_Barrows PLC', 'fraud_Abbott-Rogahn',
       'fraud_Ziemann-Waters', 'fraud_Reinger, Weissnat and Strosin',
       'fraud_Heathcote, Yost and Kertzmann', 'fraud_Will Ltd',
       'fraud_Kutch-Wilderman', 'fraud_Hermiston, Russel and Price',
       'fraud_Schmidt-Larkin', 'fraud_Lang, Towne and Schuppe',
       'fraud_Weber, Thiel and Hammes',
       'fraud_Hahn, Bahringer and McLaughlin',
       'fraud_Koss, Hansen and Lueilwitz',
       'fraud_Roberts, Ryan and Smith', 'fraud_Hintz, Bauch and Smith',
       'fraud_Monahan, Hermann and Johns',
       'fraud_Bahringer, Osinski and Block',
       'fraud_Douglas, DuBuque and McKenzie', 'fraud_Hackett Group',
       'fraud_Schmeler-Howe', 'fraud_Predovic Inc', 'fraud_Langworth LLC',
       'fraud_Bartoletti and Sons', 'fraud_Bernhard-Lesch',
       'fraud_Satterfield-Lowe', 'fraud_Runte, Green and Emard',
       'fraud_Lowe, Dietrich and Erdman', 'fraud_Jast Ltd',
       'fraud_Welch, Rath and Koepp', 'fraud_Skiles LLC',
       'fraud_Ernser-Feest', 'fraud_Klein Group',
       'fraud_Torp, Muller and Borer', 'fraud_Kuhn Group',
       'fraud_Streich, Rolfson and Wilderman', 'fraud_Bins-Tillman',
       'fraud_Ankunding-Carroll', 'fraud_Hahn, Douglas and Schowalter',
       'fraud_Witting, Beer and Ernser', 'fraud_Morissette LLC',
       'fraud_Berge-Hills', 'fraud_Donnelly LLC', 'fraud_Zboncak LLC',
       'fraud_Turner, Ziemann and Lehner', 'fraud_Padberg-Sauer',
       'fraud_Schulist Ltd', 'fraud_Rau-Grant', 'fraud_Osinski Inc',
       'fraud_Berge-Ullrich', 'fraud_Wuckert-Goldner',
       'fraud_Kertzmann LLC', 'fraud_Daugherty, Pouros and Beahan',
       'fraud_Armstrong, Walter and Gottlieb', 'fraud_Conroy-Emard',
       'fraud_Moore, Williamson and Emmerich', 'fraud_Gleason and Sons',
       'fraud_Roberts, Daniel and Macejkovic', 'fraud_Turner LLC',
       'fraud_Crooks and Sons', 'fraud_Waelchi Inc',
       'fraud_Hoppe, Harris and Bednar', 'fraud_Effertz LLC',
       'fraud_Lubowitz-Walter', 'fraud_Hyatt-Blick', 'fraud_Carroll PLC',
       'fraud_Lemke and Sons', 'fraud_Treutel-King',
       'fraud_Fadel-Hilpert', 'fraud_Altenwerth-Kilback',
       'fraud_Bauch-Blanda', 'fraud_Sporer-Keebler', 'fraud_Hirthe-Beier',
       'fraud_Wisozk and Sons', 'fraud_Streich Ltd', 'fraud_Schoen Ltd',
       'fraud_Windler LLC', 'fraud_Nolan-Williamson',
       'fraud_Roob-Okuneva', 'fraud_Lakin, Ferry and Beatty',
       'fraud_Gottlieb Group', 'fraud_Harris Group', 'fraud_Fritsch LLC',
       'fraud_Corwin-Romaguera', 'fraud_Dietrich-Fadel',
       'fraud_Kling, Howe and Schneider', 'fraud_Kozey-Kuhlman',
       'fraud_Graham and Sons', 'fraud_Jacobi and Sons',
       'fraud_Eichmann, Hayes and Treutel',
       'fraud_Brown, Homenick and Lesch', 'fraud_Erdman-Schaden',
       'fraud_Durgan, Gislason and Spencer', 'fraud_Friesen-Ortiz',
       'fraud_Morissette-Schaefer', 'fraud_Nienow, Ankunding and Collier',
       'fraud_Cole, Hills and Jewess',
       'fraud_Conroy, Balistreri and Gorczany',
       'fraud_Reichel, Bradtke and Blanda',
       "fraud_O'Reilly, Mohr and Purdy", 'fraud_Ullrich Ltd',
       'fraud_Schroeder Group', 'fraud_Boyer-Haley',
       'fraud_Dare, Casper and Bartoletti',
       'fraud_Medhurst, Cartwright and Ebert', 'fraud_Quitzon-Goyette',
       'fraud_Wilkinson LLC', 'fraud_Romaguera and Sons',
       'fraud_Larkin Ltd', 'fraud_Fadel, Mertz and Rippin',
       'fraud_Huel Ltd', 'fraud_Cummerata-Hilpert', 'fraud_Zemlak Group',
       'fraud_Dare-Gibson', 'fraud_Adams-Barrows', 'fraud_Block-Hauck',
       'fraud_Howe PLC', 'fraud_Leffler-Goldner', 'fraud_Tillman LLC',
       'fraud_Pacocha-Weissnat', 'fraud_Morissette PLC',
       'fraud_Jerde-Hermann', 'fraud_Kihn, Brakus and Goyette',
       'fraud_Hills, Hegmann and Schaefer', 'fraud_Friesen Ltd',
       'fraud_Kilback and Sons', 'fraud_Ebert-Daugherty',
       'fraud_Hermiston, Pacocha and Smith', 'fraud_Auer LLC',
       'fraud_Fadel Inc', 'fraud_Daugherty-Thompson',
       'fraud_Romaguera Ltd', 'fraud_Parker-Kunde', 'fraud_Barton LLC',
       'fraud_Kassulke Inc', 'fraud_McLaughlin, Armstrong and Koepp',
       'fraud_Abernathy and Sons', 'fraud_Bahringer Group',
       'fraud_Connelly PLC', 'fraud_Willms, Kris and Bergnaum',
       'fraud_Thiel Ltd', 'fraud_Kris-Kertzmann',
       "fraud_O'Connell-Ullrich", 'fraud_Kozey-McDermott',

In [80]:
df.drop("merchant",axis = 1,inplace = True)
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\4164081178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("merchant",axis = 1,inplace = True)

,Unnamed: 0,trans_date_trans_time,cc_num,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [81]:
df["job"].unique()

array(['Psychologist, counselling', 'Special educational needs teacher',
       'Nature conservation officer', 'Patent attorney',
       'Dance movement psychotherapist', 'Transport planner',
       'Arboriculturist', 'Designer, multimedia',
       'Public affairs consultant', 'Pathologist', 'IT trainer',
       'Systems developer', 'Engineer, land', 'Systems analyst',
       'Naval architect', 'Radiographer, diagnostic',
       'Programme researcher, broadcasting/film/video', 'Energy engineer',
       'Event organiser', 'Operational researcher', 'Market researcher',
       'Probation officer', 'Leisure centre manager',
       'Corporate investment banker', 'Therapist, occupational',
       'Call centre manager', 'Police officer',
       'Education officer, museum', 'Physiotherapist', 'Network engineer',
       'Forensic psychologist', 'Geochemist',
       'Armed forces training and education officer',
       'Designer, furniture', 'Optician, dispensing',
       'Psychologist, forensic', 'Librarian, public', 'Fine artist',
       'Scientist, research (maths)', 'Research officer, trade union',
       'Tourism officer', 'Human resources officer', 'Surveyor, minerals',
       'Applications developer', 'Video editor', 'Curator',
       'Research officer, political party', 'Engineer, mining',
       'Education officer, community', 'Physicist, medical',
       'Amenity horticulturist', 'Electrical engineer',
       'Television camera operator', 'Higher education careers adviser',
       'Ambulance person', 'Dealer', 'Paediatric nurse',
       'Trading standards officer', 'Engineer, technical sales',
       'Designer, jewellery', 'Clinical biochemist',
       'Engineer, electronics', 'Water engineer', 'Science writer',
       'Film/video editor', 'Solicitor, Scotland',
       'Product/process development scientist', 'Tree surgeon',
       'Careers information officer', 'Geologist, engineering',
       'Counsellor', 'Freight forwarder',
       'Senior tax professional/tax inspector',
       'Engineer, broadcasting (operations)',
       'English as a second language teacher', 'Economist',
       'Child psychotherapist', 'Claims inspector/assessor',
       'Tourist information centre manager',
       'Exhibitions officer, museum/gallery', 'Location manager',
       'Engineer, biomedical', 'Research scientist (physical sciences)',
       'Purchasing manager', 'Editor, magazine features',
       'Operations geologist', 'Interpreter', 'Engineering geologist',
       'Agricultural consultant', 'Paramedic', 'Financial adviser',
       'Administrator, education', 'Educational psychologist',
       'Financial trader', 'Audiological scientist',
       'Scientist, audiological',
       'Administrator, charities/voluntary organisations',
       'Health service manager', 'Retail merchandiser',
       'Telecommunications researcher', 'Exercise physiologist',
       'Accounting technician', 'Product designer',
       'Waste management officer', 'Mining engineer', 'Surgeon',
       'Therapist, horticultural', 'Environmental consultant',
       'Broadcast presenter', 'Producer, radio',
       'Engineer, communications',
       'Historic buildings inspector/conservation officer',
       'Teacher, English as a foreign language', 'Materials engineer',
       'Health visitor', 'Medical secretary', 'Theatre director',
       'Technical brewer', 'Land/geomatics surveyor',
       'Engineer, structural', 'Diagnostic radiographer',
       'Television production assistant', 'Medical sales representative',
       'Building control surveyor', 'Therapist, sports',
       'Structural engineer', 'Commercial/residential surveyor',
       'Database administrator', 'Exhibition designer',
       'Training and development officer', 'Mechanical engineer',
       'Medical physicist', 'Administrator', 'Mudlogger',
       'Fisheries officer', 'Conservator, museum/gallery',
       'Programmer, multimedia', 'Cytogeneticist',
       'Multimedia programmer', 'Counselling psychologist', 'Chiropodist',
       'Teacher, early years/pre', 'Cartographer', 'Pensions consultant',
       'Primary school teacher', 'Electronics engineer',
       'Museum/gallery exhibitions officer', 'Air broker',
       'Chemical engineer', 'Advertising account executive',
       'Advertising account planner',
       'Chartered legal executive (England and Wales)',
       'Psychiatric nurse', 'Secondary school teacher',
       'Librarian, academic', 'Embryologist, clinical', 'Immunologist',
       'Television floor manager', 'Contractor', 'Health physicist',
       'Copy', 'Bookseller', 'Land', 'Chartered loss adjuster',
       'Occupational psychologist', 'Facilities manager',
       'Further education lecturer', 'Archivist', 'Investment analyst',
       'Engineer, building services', 'Psychologist, sport and exercise',
       'Journalist, newspaper', 'Doctor, hospital', 'Phytotherapist',
       'Pharmacologist', 'Horticultural therapist', 'Hydrologist',
       'Community arts worker', 'Public house manager', 'Architect',
       'Lexicographer', 'Psychotherapist, child',
       'Teacher, secondary school', 'Toxicologist',
       'Commercial horticulturist', 'Podiatrist', 'Building surveyor',
       'Architectural technologist', 'Editor, film/video',
       'Social researcher', 'Wellsite geologist', 'Minerals surveyor',
       'Designer, ceramics/pottery', 'Mental health nurse',
       'Volunteer coordinator', 'Chief Technology Officer',
       'Camera operator', 'Copywriter, advertising', 'Surveyor, mining',
       'Product manager', "Nurse, children's", 'Pension scheme manager',
       'Archaeologist', 'Sub', 'Designer, interior/spatial',
       'Futures trader', 'Chief Financial Officer',
       'Museum education officer', 'Quantity surveyor',
       'Physiological scientist', 'Loss adjuster, chartered',
       'Pilot, airline', 'Production assistant, radio',
       'Immigration officer', 'Retail banker',
       'Health and safety adviser', 'Teacher, special educational needs',
       'Jewellery designer', 'Community pharmacist',
       'Control and instrumentation engineer', 'Make',
       'Early years teacher', 'Sales professional, IT',
       'Scientist, marine', 'Intelligence analyst',
       'Clinical research associate', 'Administrator, local government',
       'Barrister', 'Engineer, control and instrumentation',
       'Clothing/textile technologist', 'Development worker, community',
       'Art therapist', 'Sales executive',
       'Armed forces logistics/support/administrative officer',
       'Optometrist', 'Insurance underwriter', 'Charity officer',
       'Civil Service fast streamer', 'Retail buyer',
       'Magazine features editor', 'Equities trader',
       'Trade mark attorney', 'Research scientist (life sciences)',
       'Psychotherapist', 'Pharmacist, community', 'Risk analyst',
       'Engineer, maintenance', 'Logistics and distribution manager',
       'Water quality scientist', 'Lecturer, further education',
       'Production assistant, television', 'Tour manager',
       'Music therapist', 'Surveyor, land/geomatics',
       'Engineer, production', 'Acupuncturist', 'Hospital doctor',
       'Teacher, primary school', 'Accountant, chartered public finance',
       'Illustrator', 'Scientist, physiological', 'Buyer, industrial',
       'Scientist, research (physical sciences)', 'Radio producer',
       'Manufacturing engineer', 'Animal technologist',
       'Production engineer', 'Biochemist, clinical',
       'Engineer, manufacturing', 'Comptroller',
       'General practice doctor', 'Designer, industrial/product',
       'Prison officer', 'Merchandiser, retail', 'Engineer, drilling',
       'Engineer, petroleum', 'Cabin crew', 'Commissioning editor',
       'Accountant, chartered certified', 'Local government officer',
       'Professor Emeritus', 'Press sub',
       'Chartered public finance accountant', 'Writer',
       'Chief Executive Officer', 'Occupational hygienist',
       'Doctor, general practice', 'Community education officer',
       'Landscape architect', 'Occupational therapist',
       'Special effects artist', 'Civil engineer, contracting',
       "Barrister's clerk", 'Travel agency manager',
       'Associate Professor', 'Neurosurgeon', 'Plant breeder/geneticist',
       'Radio broadcast assistant', 'Field seismologist',
       'Industrial/product designer', 'Metallurgist',
       "Politician's assistant", 'Insurance claims handler',
       'Theme park manager', 'Gaffer', 'Chief Strategy Officer',
       'Heritage manager', 'Ceramics designer', 'Animator',
       'Oceanographer', 'Colour technologist', 'Engineer, agricultural',
       'Therapist, drama', 'Orthoptist', 'Learning mentor',
       'Arts development officer', 'Biomedical engineer',
       'Race relations officer', 'Therapist, music', 'Retail manager',
       'Furniture designer', 'Building services engineer',
       'Maintenance engineer', 'Aid worker', 'Editor, commissioning',
       'Private music teacher', 'Scientist, biomedical',
       'Public relations account executive', 'Dispensing optician',
       'Advice worker', 'Hydrographic surveyor', 'Geoscientist',
       'Environmental health practitioner', 'Learning disability nurse',
       'Chief Operating Officer', 'Scientific laboratory technician',
       'Records manager', 'Barista', 'Marketing executive',
       'Tax inspector', 'Musician', 'Therapist, art',
       'Engineer, automotive', 'Clinical psychologist', 'Warden/ranger',
       'Surveyor, rural practice', 'Sport and exercise psychologist',
       'Education administrator', 'Chief of Staff',
       'Nurse, mental health', 'Music tutor',
       'Planning and development surveyor',
       'Teaching laboratory technician', 'Chief Marketing Officer',
       'Theatre manager', 'Quarry manager',
       'Interior and spatial designer', 'Lecturer, higher education',
       'Regulatory affairs officer', 'Secretary/administrator',
       'Chemist, analytical', 'Designer, exhibition/display',
       'Pharmacist, hospital', 'Site engineer',
       'Equality and diversity officer', 'Public librarian',
       'Town planner', 'Chartered accountant', 'Programmer, applications',
       'Manufacturing systems engineer', 'Web designer',
       'Community development worker', 'Animal nutritionist',
       'Petroleum engineer', 'Information systems manager',
       'Press photographer', 'Insurance risk surveyor', 'Soil scientist',
       'Buyer, retail', 'Public relations officer',
       'Health promotion specialist', 'Psychiatrist',
       'Visual merchandiser', 'Rural practice surveyor', 'Hotel manager',
       'Communications engineer', 'Insurance broker',
       'Radiographer, therapeutic', 'Set designer', 'Tax adviser',
       'Drilling engineer', 'Fitness centre manager', 'Farm manager',
       'Management consultant', 'Energy manager',
       'Museum/gallery conservator', 'Herbalist', 'Osteopath',
       'Statistician', 'Hospital pharmacist', 'Estate manager/land agent',
       'Sports development officer', 'Investment banker, corporate',
       'Biomedical scientist', 'Television/film/video producer',
       'Nutritional therapist', 'Company secretary', 'Production manager',
       'Magazine journalist', 'Media buyer', 'Data scientist',
       'Engineer, civil (contracting)', 'Herpetologist',
       'Garment/textile technologist', 'Scientist, research (medical)',
       'Civil Service administrator', 'Airline pilot', 'Textile designer',
       'Environmental manager', 'Furniture conservator/restorer',
       'Horticultural consultant', 'Firefighter',
       'Geophysicist/field seismologist', 'Psychologist, clinical',
       'Development worker, international aid', 'Sports administrator',
       'IT consultant', 'Presenter, broadcasting',
       'Outdoor activities/education manager', 'Field trials officer',
       'Social research officer, government',
       'English as a foreign language teacher',
       'Restaurant manager, fast food', 'Hydrogeologist',
       'Research scientist (medical)', 'Designer, television/film set',
       'Geneticist, molecular', 'Designer, textile',
       'Licensed conveyancer', 'Emergency planning/management officer',
       'Geologist, wellsite', 'Air cabin crew', 'Seismic interpreter',
       'Surveyor, hydrographic', 'Charity fundraiser', 'Stage manager',
       'Aeronautical engineer', 'Glass blower/designer', 'Ecologist',
       'Horticulturist, commercial', 'Research scientist (maths)',
       'Engineer, aeronautical',
       'Conservation officer, historic buildings', 'Art gallery manager',
       'Advertising copywriter', 'Engineer, civil (consulting)',
       'Oncologist', 'Engineer, materials',
       'Scientist, clinical (histocompatibility and immunogenetics)',
       'Investment banker, operational', 'Medical technical officer',
       'Academic librarian', 'Artist', 'Clinical cytogeneticist',
       'TEFL teacher', 'Administrator, arts', 'Teacher, adult education',
       'Catering manager', 'Environmental education officer',
       'Conservator, furniture', 'Analytical chemist',
       'Broadcast engineer', 'Media planner', 'Lawyer',
       'Producer, television/film/video'], dtype=object)

In [82]:
df.drop("job",axis = 1,inplace = True)
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\1316849228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("job",axis = 1,inplace = True)

,Unnamed: 0,trans_date_trans_time,cc_num,category,amt,first,last,gender,street,city,...,zip,lat,long,city_pop,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,28654,36.0788,-81.1781,3495,1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,99160,48.8878,-118.2105,149,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,83252,42.1808,-112.2620,4154,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,59632,46.2306,-112.1138,1939,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,24433,38.4207,-79.4629,99,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [83]:
df["dob"].unique()

array(['1988-03-09', '1978-06-21', '1962-01-19', '1967-01-12',
       '1986-03-28', '1961-06-19', '1993-08-16', '1947-08-21',
       '1941-03-07', '1974-03-28', '1990-07-13', '1966-02-14',
       '1989-02-28', '1945-12-21', '1967-08-30', '1965-06-30',
       '1952-07-06', '1938-03-15', '1946-02-02', '1980-12-21',
       '1980-11-22', '1961-02-14', '1974-07-19', '1965-07-26',
       '1946-01-02', '1962-08-13', '1971-11-05', '1967-08-02',
       '1966-12-03', '1945-03-15', '1961-05-19', '1964-12-30',
       '1964-04-22', '1977-02-22', '1970-07-20', '1984-06-04',
       '1970-10-21', '1984-12-24', '1998-10-01', '1988-04-27',
       '1987-07-18', '1971-10-14', '1987-04-23', '1942-01-06',
       '1971-01-28', '1972-07-25', '1984-09-01', '1960-01-06',
       '1986-11-06', '1954-01-05', '1970-09-27', '1994-02-09',
       '1942-11-24', '1994-11-05', '1993-10-25', '1976-10-18',
       '1981-02-15', '1974-03-13', '1926-07-12', '1966-12-21',
       '1936-03-28', '1997-08-22', '1972-05-04', '1955-06-12',
       '1990-08-13', '1967-02-04', '1974-06-21', '1962-11-11',
       '1983-07-25', '1979-01-02', '2000-06-13', '1957-03-28',
       '1955-01-05', '1976-02-26', '1982-01-07', '1935-09-08',
       '1975-04-30', '1977-04-28', '1954-05-25', '1946-04-03',
       '1975-07-31', '1998-03-19', '1974-12-23', '1995-07-12',
       '1989-11-24', '1983-08-25', '1984-06-03', '1935-08-15',
       '1995-04-19', '1976-09-08', '1946-08-24', '1971-08-20',
       '1957-03-06', '1970-09-11', '1977-01-04', '1986-06-11',
       '1989-04-08', '1986-06-20', '1980-12-16', '1978-07-08',
       '1957-12-29', '1972-06-14', '1935-04-15', '1927-09-09',
       '1928-10-01', '1950-08-19', '1958-06-26', '1926-09-14',
       '1935-02-10', '1962-04-12', '1951-02-05', '1985-03-21',
       '1990-05-03', '1945-09-20', '1961-01-21', '1972-11-28',
       '1972-07-01', '1958-08-14', '1985-09-02', '2001-07-26',
       '1929-05-06', '1960-06-14', '1954-06-14', '1977-10-19',
       '1971-11-02', '1950-11-27', '1963-05-23', '1948-11-14',
       '1966-11-10', '1990-10-15', '1963-04-22', '1954-12-10',
       '1968-07-01', '1973-04-01', '1988-09-15', '1988-04-15',
       '1959-09-27', '1999-06-06', '1985-01-01', '2003-05-07',
       '1957-01-23', '1927-12-11', '1981-06-22', '1962-06-04',
       '1990-06-25', '1960-01-16', '1954-07-15', '1984-07-03',
       '1971-08-06', '1950-04-05', '1967-05-28', '1952-10-13',
       '1983-10-14', '1969-03-02', '1968-10-06', '1931-01-26',
       '1940-11-11', '1987-11-18', '1965-12-15', '1962-10-16',
       '1981-07-05', '1934-03-19', '1989-07-17', '1992-05-09',
       '1982-05-20', '1929-08-23', '1971-03-26', '1995-05-25',
       '1997-06-04', '1951-12-04', '1967-05-27', '1939-09-19',
       '1986-05-02', '1936-03-27', '1958-06-11', '1953-03-30',
       '1997-03-12', '1963-12-29', '1957-04-17', '1998-10-07',
       '1981-10-24', '1971-04-25', '1970-02-22', '1956-01-09',
       '1968-06-18', '1969-10-30', '1995-10-17', '1978-01-15',
       '1954-07-05', '1926-06-26', '1960-01-20', '1964-01-04',
       '1945-08-19', '1934-10-06', '1974-10-27', '1951-11-08',
       '1963-06-22', '1963-04-04', '1968-02-10', '1993-07-05',
       '1978-03-06', '1980-05-18', '1970-11-12', '1977-06-07',
       '1982-02-10', '1926-08-27', '1969-09-21', '1970-03-13',
       '1974-03-10', '1939-11-09', '1986-12-13', '1958-04-06',
       '1973-07-28', '1953-01-20', '1977-08-16', '2004-05-08',
       '1992-01-20', '2005-01-29', '1974-02-15', '1972-05-23',
       '1945-11-04', '1958-09-20', '1972-10-18', '1937-03-17',
       '1961-10-24', '1983-07-24', '1955-05-06', '1951-01-15',
       '1954-06-30', '1956-01-24', '1958-09-02', '1948-06-30',
       '1969-07-24', '1954-08-22', '1961-09-10', '1980-08-18',
       '1964-08-23', '1978-08-27', '1969-08-04', '1988-03-25',
       '1979-06-24', '1985-04-15', '1973-05-07', '1975-07-07',
       '1978-03-04', '1959-07-30', '1952-04-02', '1928-07-15',
       '1980-09-15', '1956-09-15', '1986-12-17', '1969-11-22',
       '1954-07-14', '1952-09-27', '1973-02-14', '1960-02-01',
       '1942-04-03', '1933-03-15', '1964-02-13', '1963-02-09',
       '1974-11-02', '1929-05-30', '1964-11-17', '1934-06-23',
       '1960-04-03', '1987-05-19', '1955-07-25', '1976-09-17',
       '1996-04-10', '1944-07-26', '1988-02-15', '1969-02-22',
       '1993-04-08', '1970-06-09', '1991-03-13', '1964-08-08',
       '1953-12-08', '1975-12-28', '1959-05-10', '1972-10-04',
       '1997-07-05', '1990-11-23', '1962-09-27', '1975-07-13',
       '1967-09-16', '1971-02-11', '1982-07-30', '1973-01-21',
       '1993-10-12', '1964-02-15', '1969-11-01', '1973-05-16',
       '1990-11-07', '1956-05-30', '1950-05-27', '1980-08-17',
       '1974-10-15', '1961-01-31', '1973-06-09', '1969-12-22',
       '1962-05-04', '1984-07-05', '1927-10-24', '1967-01-24',
       '1976-03-26', '1983-06-23', '1990-01-24', '1965-04-13',
       '1957-04-05', '1966-01-04', '1979-04-12', '1983-10-12',
       '2001-06-22', '1991-10-13', '1993-11-17', '1974-11-20',
       '1963-08-04', '1956-09-01', '1981-05-06', '1995-03-13',
       '1976-09-29', '1958-01-01', '1979-12-11', '1976-05-16',
       '1984-08-01', '1953-05-23', '1991-04-13', '1949-10-04',
       '1958-10-29', '1955-11-07', '1973-10-19', '1968-06-24',
       '1951-09-03', '1955-11-10', '1964-04-06', '1962-02-14',
       '1991-10-04', '1976-06-15', '1962-04-05', '1999-09-11',
       '1989-05-14', '1968-02-09', '1950-11-20', '1992-06-19',
       '1936-11-05', '1966-09-16', '1954-01-06', '1987-09-26',
       '1953-07-30', '1942-05-04', '1968-07-24', '1982-08-01',
       '1963-06-13', '1993-05-14', '1986-03-14', '1969-09-15',
       '1987-05-05', '1974-12-05', '1975-06-29', '1941-04-23',
       '1948-05-01', '1961-09-03', '1986-04-28', '1943-05-28',
       '1953-12-25', '1954-01-29', '1992-07-23', '1976-01-02',
       '1941-10-16', '1972-04-18', '1993-11-02', '1991-06-05',
       '1984-11-06', '1959-10-07', '1951-06-13', '1975-12-20',
       '1960-01-13', '1991-01-28', '1970-03-14', '1961-04-25',
       '1958-07-28', '1988-09-02', '1998-07-29', '1971-12-10',
       '1973-07-13', '1999-10-25', '1958-10-26', '1967-06-20',
       '1966-06-07', '1986-05-01', '1984-03-03', '1976-10-09',
       '1955-01-20', '1956-10-08', '1965-04-27', '1999-11-30',
       '1966-05-22', '1949-10-13', '1957-01-15', '1942-04-17',
       '1941-11-16', '1995-07-08', '1983-02-08', '1961-04-22',
       '1969-05-16', '1968-05-13', '1970-10-09', '1978-08-08',
       '1968-11-22', '1960-11-19', '1976-06-30', '1952-03-08',
       '1972-08-09', '1991-03-29', '1990-10-28', '1997-11-18',
       '1952-01-29', '1992-11-27', '1987-09-19', '1985-12-27',
       '1970-01-08', '1983-08-24', '1956-05-02', '1989-10-06',
       '1965-09-15', '1979-07-03', '1986-01-30', '1968-05-16',
       '1994-03-13', '1957-08-08', '1987-04-24', '1935-01-29',
       '1941-03-30', '1978-01-22', '1982-07-02', '1959-05-28',
       '1939-03-09', '1986-11-12', '1959-08-05', '1962-03-20',
       '1985-08-29', '1980-03-18', '1990-11-09', '1974-05-18',
       '1972-07-18', '1940-09-13', '1991-08-19', '1994-11-24',
       '1974-12-24', '1981-08-29', '1988-09-19', '1973-02-07',
       '1967-06-19', '1977-08-12', '1955-07-06', '1978-12-18',
       '1965-11-11', '1946-08-30', '1949-03-20', '1986-07-23',
       '1979-09-03', '1958-02-17', '1977-06-14', '1950-03-25',
       '1957-11-12', '1994-04-22', '1982-02-08', '1974-09-14',
       '1966-01-21', '1964-06-22', '1927-05-25', '1984-03-06',
       '1973-05-27', '1938-09-08', '1987-02-22', '1971-08-05',
       '1961-11-24', '1935-06-29', '1978-05-23', '1985-06-18',
       '1976-11-21', '1957-08-30', '1953-04-19', '1999-12-27',
       '1971-07-02', '1977-03-23', '1980-01-09', '1974-01-03',
       '1992-10-07', '1988-10-26', '1980-07-12', '1930-08-13',
       '1967-04-09', '1988-08-04', '1974-12-28', '1987-04-29',
       '1956-06-22', '1983-06-14', '1985-05-25', '1986-03-31',
       '1973-12-26', '1977-12-16', '1972-01-20', '1936-05-01',
       '1976-09-12', '1966-02-21', '1991-05-01', '1989-03-09',
       '1948-05-31', '1965-04-07', '1982-05-28', '1932-03-10',
       '1946-11-01', '1993-02-26', '1943-06-30', '1990-06-08',
       '1931-03-07', '2000-06-09', '1975-04-16', '1986-01-18',
       '1981-08-10', '1987-01-27', '1989-10-28', '1978-09-30',
       '1983-09-02', '1989-12-17', '1993-09-11', '1985-03-19',
       '1979-04-30', '1962-02-13', '1946-08-11', '1985-12-03',
       '1990-10-19', '1978-10-26', '1994-10-07', '1972-09-22',
       '1973-11-14', '1960-03-01', '1995-12-28', '1937-02-01',
       '1956-03-02', '1991-02-03', '1974-04-16', '1939-11-04',
       '1997-01-02', '1979-01-21', '1966-02-13', '1983-06-12',
       '1984-07-20', '1983-07-10', '2004-12-30', '1963-05-19',
       '1993-10-07', '1983-06-13', '1999-03-05', '1993-10-05',
       '1970-04-17', '1987-10-28', '1991-02-04', '1980-09-18',
       '1986-02-17', '1988-07-28', '1974-05-30', '1984-02-14',
       '1932-11-19', '1975-06-02', '1988-09-06', '1958-09-10',
       '1978-10-05', '1989-02-08', '1949-11-17', '1994-11-12',
       '1980-07-30', '2001-07-05', '1997-12-27', '1963-06-30',
       '1940-08-23', '1933-04-02', '1949-11-16', '2003-09-14',
       '1985-06-20', '1987-05-23', '1995-04-22', '1978-10-01',
       '1966-08-08', '1986-11-24', '1982-02-11', '1992-07-24',
       '1999-06-19', '1998-05-20', '1955-06-26', '1990-01-17',
       '1987-07-25', '1961-12-14', '1990-12-18', '1959-06-28',
       '1982-02-05', '1970-01-18', '1972-06-12', '1987-06-13',
       '1992-10-03', '1973-05-04', '1988-01-04', '1943-12-15',
       '1945-05-05', '1997-09-22', '1955-02-01', '1963-12-28',
       '1978-12-25', '1960-08-05', '1965-03-25', '1998-02-03',
       '1984-02-07', '1984-05-19', '1969-09-11', '1984-02-29',
       '1994-07-27', '1964-02-18', '1991-10-22', '1995-08-16',
       '1940-09-17', '1986-05-07', '1939-04-14', '1984-05-04',
       '1941-07-31', '1995-11-29', '1960-03-12', '1955-04-03',
       '2000-08-28', '1972-02-15', '1944-11-11', '2004-03-18',
       '1986-12-31', '1991-04-11', '1995-09-11', '1986-04-15',
       '1982-01-16', '1986-08-17', '1997-07-01', '1990-05-22',
       '1960-12-13', '1977-06-12', '1969-01-14', '1985-08-31',
       '1963-06-04', '1952-05-07', '1981-11-29', '1952-12-07',
       '1959-06-06', '1987-09-08', '1993-11-24', '1993-05-10',
       '1995-01-15', '1936-07-22', '1967-05-05', '1996-11-12',
       '1957-04-25', '1977-07-17', '1973-04-06', '1968-03-19',
       '1989-07-08', '1955-01-13', '1998-03-18', '1994-03-01',
       '1994-02-16', '1990-02-25', '1992-12-29', '1988-11-01',
       '1976-04-11', '1968-03-24', '1990-04-25', '1985-08-21',
       '1978-11-30', '1930-10-21', '1992-11-20', '1970-11-09',
       '1949-04-24', '1987-02-14', '1993-03-23', '1972-01-03',
       '1965-04-01', '1973-10-14', '1972-09-12', '1991-01-01',
       '1987-02-13', '1995-12-04', '1976-01-10', '1997-12-26',
       '1961-05-13', '1984-12-16', '1973-09-22', '1988-03-21',
       '1963-07-14', '1948-11-30', '1967-08-24', '1962-04-30',
       '1968-05-29', '1966-09-19', '1980-03-24', '1947-07-15',
       '1972-10-05', '1976-12-10', '1962-05-13', '1962-06-27',
       '1962-11-18', '1956-05-15', '1972-03-05', '1956-12-13',
       '1979-12-27', '1982-12-27', '1985-05-13', '1953-04-13',
       '1985-12-08', '1985-07-08', '1975-10-11', '1991-04-22',
       '1997-10-23', '1970-06-27', '1999-05-31', '1961-12-05',
       '1971-10-19', '1945-11-26', '1987-10-26', '1968-01-28',
       '1962-03-04', '1971-09-01', '1943-12-17', '1976-12-14',
       '1979-10-22', '1968-09-19', '1939-06-01', '1975-11-30',
       '1985-04-03', '1995-10-10', '1999-09-01', '1991-07-06',
       '1985-03-31', '1972-12-31', '1929-03-19', '1989-12-10',
       '1994-05-31', '1972-01-05', '1987-08-16', '1944-05-14',
       '1949-06-09', '2000-02-20', '1985-04-04', '1972-03-28',
       '1957-12-26', '1932-09-17', '1979-08-14', '1967-10-18',
       '1969-05-01', '1967-03-17', '1982-04-19', '1950-09-15',
       '1976-04-12', '1991-01-31', '1981-01-06', '1975-01-26',
       '1993-05-27', '2004-06-19', '1967-10-04', '1993-09-29',
       '1970-11-20', '1950-04-17', '1953-03-19', '1967-03-30',
       '1993-04-29', '1948-04-11', '1929-04-22', '1997-11-23',
       '1976-01-15', '1960-04-08', '1930-02-28', '1945-12-07',
       '1960-10-28', '1979-01-26', '1985-09-01', '1961-12-18',
       '2000-08-16', '1969-11-20', '1971-12-12', '1966-05-10',
       '1949-08-14', '1979-01-08', '1946-03-21', '1965-02-03',
       '1983-03-20', '1954-07-21', '1987-10-27', '1981-03-29',
       '1928-04-02', '1981-03-04', '1952-12-05', '1997-08-04',
       '1947-10-27', '1953-10-18', '1967-03-12', '1948-09-07',
       '1966-06-24', '1956-09-14', '1965-11-06', '1972-09-13',
       '1983-11-10', '1992-10-08', '1994-07-09', '1984-09-13',
       '1966-06-19', '1967-09-30', '1990-06-21', '1994-12-08',
       '1990-09-12', '1966-05-29', '1995-08-30', '1982-06-27',
       '1978-10-04', '1959-03-31', '1975-09-11', '1977-05-18',
       '1991-08-21', '1999-06-28', '1975-12-24', '1931-09-12',
       '1947-08-14', '1962-03-19', '1962-12-06', '1961-09-28',
       '1987-02-26', '1955-12-04', '1934-02-09', '1986-04-03',
       '1964-03-15', '1969-03-20', '1948-03-22', '1966-12-15',
       '1933-03-01', '1987-09-22', '1981-01-26', '1959-01-15',
       '2001-12-19', '1982-02-19', '1928-06-26', '1964-03-16',
       '1964-06-25', '1965-09-27', '1971-01-19', '1976-05-24',
       '1927-08-25', '1973-10-09', '1975-06-25', '1988-04-09',
       '1975-06-01', '1942-04-02', '1981-02-18', '1964-08-18',
       '1967-09-23', '1969-12-12', '1929-04-07', '1940-09-06',
       '1937-02-06', '1990-01-13', '1990-06-13', '1986-10-17',
       '1984-08-31', '1950-12-14', '1969-09-08', '1989-08-16',
       '1956-05-01', '1961-11-07', '1959-06-18', '1997-01-18',
       '1975-10-07', '1924-10-30', '1959-10-19', '1952-05-26',
       '1967-10-28', '1996-01-11', '1983-01-21', '1971-11-26',
       '1959-05-30', '2001-07-10', '1985-01-02', '1972-08-15',
       '1965-11-21', '1963-09-11', '1983-01-08', '1961-07-31',
       '1972-07-29', '1961-09-13', '1957-06-12', '1987-11-30',
       '1967-08-28', '1951-03-31', '1989-10-19'], dtype=object)

In [84]:
df.drop("dob",axis = 1,inplace = True)
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\1862615931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("dob",axis = 1,inplace = True)

,Unnamed: 0,trans_date_trans_time,cc_num,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [85]:
df["category"].value_counts

<bound method IndexOpsMixin.value_counts of 0             misc_net
1          grocery_pos
2        entertainment
3        gas_transport
4             misc_pos
             ...
19995      grocery_pos
19996     shopping_pos
19997      grocery_net
19998      grocery_pos
19999    gas_transport
Name: category, Length: 20000, dtype: object>

In [86]:
df.drop("category",axis = 1,inplace = True)
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\1663258367.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("category",axis = 1,inplace = True)

,Unnamed: 0,trans_date_trans_time,cc_num,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [87]:
df.drop("Unnamed: 0",axis = 1,inplace = True)
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\1285777174.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("Unnamed: 0",axis = 1,inplace = True)

,trans_date_trans_time,cc_num,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

using label encoder on the gender column

In [88]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["gender"] = le.fit_transform(df["gender"])
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\3228762951.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["gender"] = le.fit_transform(df["gender"])

,trans_date_trans_time,cc_num,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,4.97,Jennifer,Banks,0,561 Perry Cove,Moravian Falls,NC,28654,36.0788,-81.1781,3495,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,107.23,Stephanie,Gill,0,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,220.11,Edward,Sanchez,1,594 White Dale Suite 530,Malad City,ID,83252,42.1808,-112.2620,4154,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,45.00,Jeremy,White,1,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,-112.1138,1939,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,41.96,Tyler,Garcia,1,408 Bradley Rest,Doe Hill,VA,24433,38.4207,-79.4629,99,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [89]:
df["city"].value_counts

<bound method IndexOpsMixin.value_counts of 0         Moravian Falls
1                 Orient
2             Malad City
3                Boulder
4               Doe Hill
              ...
19995    Mountain Center
19996        Marienville
19997         Kensington
19998            Zaleski
19999        Coffeeville
Name: city, Length: 20000, dtype: object>

In [90]:
df.drop("city",axis = 1,inplace = True)
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\3968786824.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("city",axis = 1,inplace = True)

,trans_date_trans_time,cc_num,amt,first,last,gender,street,state,zip,lat,long,city_pop,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,4.97,Jennifer,Banks,0,561 Perry Cove,NC,28654,36.0788,-81.1781,3495,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,107.23,Stephanie,Gill,0,43039 Riley Greens Suite 393,WA,99160,48.8878,-118.2105,149,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,220.11,Edward,Sanchez,1,594 White Dale Suite 530,ID,83252,42.1808,-112.2620,4154,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,45.00,Jeremy,White,1,9443 Cynthia Court Apt. 038,MT,59632,46.2306,-112.1138,1939,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,41.96,Tyler,Garcia,1,408 Bradley Rest,VA,24433,38.4207,-79.4629,99,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [91]:
deleted_columns = df[["trans_date_trans_time","cc_num","first","last","street","state","zip","lat","long","trans_num","unix_time"]]
df.drop(deleted_columns,axis = 1,inplace = True)
df.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\3913002067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(deleted_columns,axis = 1,inplace = True)

      amt  gender  city_pop  merch_lat  merch_long  is_fraud
0    4.97       0      3495  36.011293  -82.048315         0
1  107.23       0       149  49.159047 -118.186462         0
2  220.11       1      4154  43.150704 -112.154481         0
3   45.00       1      1939  47.034331 -112.561071         0
4   41.96       1        99  38.674999  -78.632459         0

In [92]:
X_train = df.drop("is_fraud",axis=1)
y_train = df["is_fraud"]

importing our test cv

In [94]:
df_test = pd.read_csv(r"C:\Users\rishi\Desktop\CodSoft\fraudTest.csv.zip")
df_test.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [96]:
df_test = df_test.head(20000)

In [97]:
df_test["gender"] = le.fit_transform(df["gender"])
df_test.head()

C:\Users\rishi\AppData\Local\Temp\ipykernel_11168\1347591571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test["gender"] = le.fit_transform(df["gender"])

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,0,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,0,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,1,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,1,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,1,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [98]:
X_test = df_test[["amt","gender","city_pop","merch_lat","merch_long"]]
y_test = df_test["is_fraud"]

importing the models

In [99]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [105]:
from sklearn.tree import DecisionTreeClassifier
model1 = DecisionTreeClassifier()

In [106]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier(n_estimators= 40)

In [107]:
from sklearn.model_selection import cross_val_score

In [113]:
score_lr = cross_val_score(LogisticRegression(),X_train,y_train)
print(score_lr)

c:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[0.992   0.99125 0.99225 0.9915  0.991  ]

In [126]:
score_dtc = cross_val_score(DecisionTreeClassifier(),X_train,y_train)
print(score_dtc)

[0.9905 0.989  0.9915 0.989  0.9915]

In [127]:
score_rfc = cross_val_score(RandomForestClassifier(n_estimators= 40),X_train,y_train)
print(score_rfc)

[0.9935  0.99225 0.995   0.9935  0.993  ]

By comparing the scores we can see that random forest classifier is the best model.

In [117]:
model2.fit(X_train,y_train)

RandomForestClassifier(n_estimators=40)

In [119]:
model2.score(X_test,y_test)

0.9964

In [121]:
model2.predict(X_test[:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [122]:
y_pred = model2.predict(X_test)